delete from despesa;
delete from fatura_cartao;
delete from cartao;
delete from log_movimentacao;
delete from movimentacao_resumo;
delete from movimentacao;
delete from pagamento;
delete from conta;
delete from cliente;